// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRHD4xdPW-dit5-OoHKCyUXdpgKFQdqAU',
    appId: '1:526737533468:android:cd39c70dc4813439844dd9',
    messagingSenderId: '526737533468',
    projectId: 'couple-app-16b9b',
    databaseURL: 'https://couple-app-16b9b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'couple-app-16b9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChEV67qjZeEyjAUysNqj6AeIZBWEuujj4',
    appId: '1:526737533468:ios:9e9e15aed24050e5844dd9',
    messagingSenderId: '526737533468',
    projectId: 'couple-app-16b9b',
    databaseURL: 'https://couple-app-16b9b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'couple-app-16b9b.appspot.com',
    iosBundleId: 'com.example.coupleMessenger',
  );
}
